# This is a basic workflow to help you get started with Actions

name: master-Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.0
        with:
         files: '["**/appconfig.production.json"]'
        env:
          remoteServiceBaseUrl: ${{ secrets.CET_URL_STAGING }}
          appBaseUrl: ${{ secrets.CET_URL_STAGING }}
         
      - name: Check value
        run: cat ../src/BoilerPlateDemo_App.Web.Host/src/assets/appconfig.production.json
      
      - name: Build Docker Image
        run: |
          CURRENT_BRANCH="${GITHUB_REF##*/}"
          docker build -t boilerplatedemo:$CURRENT_BRANCH . --file Dockerfile
          
      - name: Run Docker Image
        run: |
          docker-compose up -d
        working-directory: /home/admin/boilerplatedemo
